---
# Attic Secrets Template (Auth-Free Mode)
#
# This is a TEMPLATE file showing the structure of secrets used by Attic.
# DO NOT store actual secret values in this file.
#
# Production secrets are managed via:
# 1. OpenTofu (tofu/stacks/attic/main.tf) - Primary method
# 2. GitLab CI/CD variables
#
# Authentication is DISABLED for Bates internal network deployment.
# The cache operates in public read/write mode.
#
# To create secrets manually (development only):
#   kubectl create secret generic attic-secrets \
#     --from-literal=DATABASE_URL="postgresql://..." \
#     --from-literal=AWS_ACCESS_KEY_ID="<access-key>" \
#     --from-literal=AWS_SECRET_ACCESS_KEY="<secret-key>" \
#     -n attic-cache

# =============================================================================
# Core Attic Secrets (Simplified - No Auth)
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: attic-secrets
  namespace: attic-cache
  labels:
    app.kubernetes.io/name: attic
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: opentofu
    app.kubernetes.io/part-of: nix-cache
  annotations:
    description: "Core secrets for Attic server operation (auth-free mode)"
type: Opaque
stringData:
  # PostgreSQL connection URL
  # Format: postgresql://user:password@host:port/database?sslmode=require
  DATABASE_URL: "<postgresql-connection-string>"

  # S3 credentials for NAR storage
  AWS_ACCESS_KEY_ID: "<s3-access-key>"
  AWS_SECRET_ACCESS_KEY: "<s3-secret-key>"
